- .github/workflows/pull-request.yml
- Add PR build workflow with codecov
> Add PR build workflow

- .github/workflows/pull-request.yml
- Temporarily remove if check for `github.event_name == 'pull_request'` from the pull-request.yml
> Temporarily remove if check for `github.event_name == 'pull_request'` from the pull-request.yml

- gradle.properties
- Bump ballerinaLang version to `2201.0.1`
> Bump ballerinaLang version to `2201.0.1`

- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionSignatureGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/TypesGenerator.java
> Add mutation support and missing identifiers
> Add mutation support and missing identifiers
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have …
> Add mutation support and missing identifiers

- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/TypesGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/graphql/components/ExtendedFragmentDefinition.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/graphql/components/SelectionData.java
- graphql-cli/src/test/java/io/ballerina/graphql/common/TestUtils.java
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/TypesGeneratorTest.java
- graphql-cli/src/test/resources/expectedGenCode/types/expectedFragmentTypes.bal
- graphql-cli/src/test/resources/expectedGenCode/types/expectedInputRecords.bal
- graphql-cli/src/test/resources/expectedGenCode/types/expectedQueryResponseRecords.bal
- graphql-cli/src/test/resources/expectedGenCode/types/expectedTypes.bal
- graphql-cli/src/test/resources/specs/queries/typesGenTests/country-queries.graphql
- graphql-cli/src/test/resources/specs/queries/typesGenTests/fragment-examples.graphql
- graphql-cli/src/test/resources/specs/typesGenTests/country.graphql
- graphql-cli/src/test/resources/specs/typesGenTests/fragment-graphql.config.yaml
- graphql-cli/src/test/resources/specs/typesGenTests/graphql.config.yaml
- graphql-cli/src/test/resources/testng.xml
- Add support for Fragments
- Fix https://github.com/ballerina-platform/graphql-tools/issues/23
- Fix https://github.com/ballerina-platform/graphql-tools/issues/21
- Fix https://github.com/ballerina-platform/graphql-tools/issues/27
- Fix https://github.com/ballerina-platform/graphql-tools/issues/30
> Add support for Fragments

- gradle.properties
> Bump tool version to 0.0.2-SNAPSHOT
> 
Ballerina Version: 2201.0.1
Java SDK: 11
> Bump tool version to 0.0.2-SNAPSHOT

- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/AuthConfigGenerator.java
- graphql-cli/src/test/resources/expectedGenCode/auth/basicClientConfig.bal
- graphql-cli/src/test/resources/expectedGenCode/auth/clientConfig.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/github/git_queries_client.bal
> 
Support breaking changes of http version 2.4.0 in generated client code.
Resolves https://github.com/ballerina-platform/graphql-tools/issues/72
Generated Client Config
```
public type ClientConfig record {|
http:BearerTokenConfig auth;
string httpVersion = "1.1";
http:ClientHttp1Settings http1Settings = {};
http:ClientHttp2Settings http2Settings = {};
decimal timeout = 60;
string forwarded = "disable";
http:FollowRedirects? followRedirects = ();
http:PoolConfiguration? poolConfig = ();
http:CacheConfig cache = {};
http:Compression compression = http:COMPRESSION_AUTO;
http:CircuitBreakerConfig? circuitBreaker = ();
http:RetryConfig? retryConfig = ();
http:CookieConfig? cookieConfig = ();
http:ResponseLimitConfigs responseLimits = {};
http:ClientSecureSocket? secureSocket = ();
|};
``` …
> Support http module version 2.4.0 breaking changes

- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/ClientGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
> Fix createFunctionBodyBlockNode and createClassDefinitionNode call by adding a `null` for optional semicolon token parameter.
> …
> Fix NodeFactory function calls

- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
Fix `createFunctionBodyBlockNode` calls by adding a null for optional semicolon token parameter.
> Link to the PR for changes to …
> Update NodeFactory usages

- .github/workflows/build-timestamped-master.yml
> Update branch for timestamp build

- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/ClientGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/ConfigTypesGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionSignatureGenerator.java
- graphql-cli/src/main/resources/templates/config_types_graphql.bal
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGeneratorTest.java
- graphql-cli/src/test/resources/expectedGenCode/client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/config_types.bal
- graphql-cli/src/test/resources/expectedGenCode/client/basicAuthClientConfig/config_types.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientAndAPIKeysConfig/client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientAndAPIKeysConfig/config_types.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/config_types.bal
- graphql-cli/src/test/resources/expectedGenCode/client/config_types.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignature.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignatureWithApiKeysConfig.bal
Update http client config generation
Fixes https://github.com/wso2-enterprise/choreo/issues/14786
Implemented design
- **Category1** (No Auth)
```ballerina
public type ConnectionConfig record {|
http:HttpVersion httpVersion = http:HTTP_2_0;
ClientHttp1Settings http1Settings?;
http:ClientHttp2Settings http2Settings?;
decimal timeout = 60;
string forwarded = "disable";
http:PoolConfiguration poolConfig?;
http:CacheConfig cache?;
http:Compression compression = http:COMPRESSION_AUTO;
http:CircuitBreakerConfig circuitBreaker?;
http:RetryConfig retryConfig?;
http:ResponseLimitConfigs responseLimits?;
http:ClientSecureSocket secureSocket?;
http:ProxyConfig …
```
> Update GraphQL tool with latest module changes & client config generation

- gradle.properties
- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-tool-idl-plugin/src/main/java/io/ballerina/graphql/idl/client/GraphQLToolIDLPlugin.java
- graphql-tool-idl-plugin/src/test/java/io/ballerina/graphql/idl/client/IDLClientGenPluginNegativeTests.java
- graphql-tool-idl-plugin/src/test/java/io/ballerina/graphql/idl/client/IDLClientGenPluginTests.java
- graphql-tool-idl-plugin/src/test/java/io/ballerina/graphql/idl/client/TestUtils.java
- graphql-tool-idl-plugin/src/test/resources/graphql-client-projects/project_02/main.bal
- graphql-tool-idl-plugin/src/test/resources/graphql-client-projects/project_09/graphql.config.yaml
- graphql-tool-idl-plugin/src/test/resources/graphql-client-projects/project_09/main.bal
> Update IDL support to align with lang changes

- build.gradle
- settings.gradle
Temporarily disable IDL support
> Disable IDL support 

- gradle.properties
> Update lang version to 2201.3.0-rc2.2

- README.md
>$subject
Part of: [#3737](https://github.com/ballerina-platform/ballerina-standard-library/issues/3737)
> Update the Readme File with SDL Schema Generation Info

- gradle.properties
> Sync with Master Branch

- gradle.properties
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
> Link to the PR for changes to the …
> Update versions for type-reference support

- graphql-cli/build.gradle
> Update Gradle Build Script

- gradle.properties
- graphql-cli/build.gradle
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service3.graphql
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/main.bal
- graphql-cli/src/test/resources/graphqlServices/valid/service1.bal
- graphql-cli/src/test/resources/graphqlServices/valid/service3.bal
Fixes: [#3800](https://github.com/ballerina-platform/ballerina-standard-library/issues/3800)
> Update the Schema Geneartion Tests with Enum Documentation

- graphql-cli/build.gradle
> Update CLI Gradle Script

- build.gradle
- gradle.properties
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/project_2/Ballerina.toml
> Remove unnecessary dependencies

- build.gradle
- gradle.properties
- graphql-cli/build.gradle
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/project_2/Ballerina.toml
> Add sub project dependencies

- build.gradle
- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-cli/src/test/resources/expectedSchemas/schema_gql.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_gql_hello_service_new.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql_docs.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service3.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service6.graphql
- graphql-cli/src/test/resources/graphqlServices/valid/service10.bal
- graphql-schema-file-generator/src/main/java/io/ballerina/graphql/schema/generator/SdlSchemaGenerator.java
>$subject
Fixes: [#3920](https://github.com/ballerina-platform/ballerina-standard-library/issues/3920)
> Update Tests with Block String Documentation

- build.gradle
- gradle.properties
- graphql-cli/build.gradle
- graphql-schema-file-generator/build.gradle
> Update ballerina lang version

- graphql-cli/build.gradle
> Enable Test Logging

- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-cli/src/test/resources/expectedSchemas/schema_gql_hello_service_new.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service_3.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service_6.graphql
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/main.bal
- graphql-cli/src/test/resources/graphqlServices/valid/project_2/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/service_1.bal
- graphql-cli/src/test/resources/graphqlServices/valid/service_3.bal
- graphql-cli/src/test/resources/graphqlServices/valid/service_6.bal
> Update schema generation tests

- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/project_2/Ballerina.toml
> Add Test for Documentation

- build.gradle
- graphql-cli/build.gradle
- graphql-cli/src/test/resources/graphqlServices/valid/project_1/Ballerina.toml
- graphql-cli/src/test/resources/graphqlServices/valid/project_2/Ballerina.toml
- graphql-schema-file-generator/build.gradle
> Add Missing Dependency in Subprojects

- gradle.properties
> Update versions for 2201.4.0-rc1

- gradle.properties
> Update versions for 2201.4.0-rc2

- gradle.properties
> Bump dependency versions for 2201.4.0

- gradle.properties
> Update HTTP and Oauth2 timestamped versions

- gradle.properties
- graphql-schema-file-generator/src/main/java/io/ballerina/graphql/schema/utils/Utils.java
> Update GraphQL Version

- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
> Update the local schema to match with remote schema

- gradle.properties
> Update version for release 0.4.1

- gradle.properties
> Sync master with release branch

- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
> Update schema changes in 0.4.x releases

- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
> Update 0.3.x releases with schema changes

- gradle.properties
> Update gradle.properties for release 0.5.0

- gradle.properties
> Update versions for release 0.5.0

- gradle.properties
> Sync release branch

- gradle.properties
> Fix vulnerability in org.json dependency

- gradle.properties
> Update lang version for release 0.3.2

- build.gradle
- gradle.properties
Fixes: [#170](https://github.com/ballerina-platform/graphql-tools/issues/170)
> Update Dependecy Versions

- gradle.properties
> [master] Fix vulnerability issue

- gradle.properties
> Fix vulnerability issue with Json dependency

- .github/workflows/publish-release.yaml
- gradle.properties
> Bump the Dependency Versions and Fix Release Workflow

- .github/workflows/build-timestamped-master.yml
- .github/workflows/publish-release.yaml
- .github/workflows/pull-request.yml
- README.md
- build.gradle
- config/checkstyle/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- graphql-cli/build.gradle
- graphql-cli/src/main/java/io/ballerina/graphql/cmd/Utils.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/TypesGenerator.java
- graphql-schema-file-generator/build.gradle
- graphql-tool-idl-plugin/build.gradle
- settings.gradle
> Migrate to Java 17

- build.gradle
> Add required dependency on 'generatePomFileForMavenJavaPublication'

- gradle.properties
> [release-0.7.0] Update version for Ballerina 2201.7.0 release

- README.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Change gradle version to 7.6.2

- gradle.properties
> Bump the GraphQL module and ballerina lang versions

- .github/workflows/pull-request.yml
> Stop running pull request workflow on push

- gradle.properties
> Merge commits from master into Java 17 migration branch

- build.gradle
> Fix incremental build

- .github/workflows/build-timestamped-master.yml
- .github/workflows/pull-request.yml
> Update java-version to 17.0.7

- gradle.properties
- graphql-cli/src/main/java/io/ballerina/graphql/cmd/Utils.java
Fixes: [#218](https://github.com/ballerina-platform/graphql-tools/issues/218)
> [2201.7.x] Fix 'NoSuchMethodError' in Client Generation

- graphql-cli/src/test/java/io/ballerina/graphql/cmd/IntrospectorTest.java
- graphql-code-generator/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-code-generator/src/main/java/io/ballerina/graphql/generator/client/Introspector.java
Fixes: [#218](https://github.com/ballerina-platform/graphql-tools/issues/218)
> Fix Client Generation Failure

- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-cli/src/test/resources/expectedSchemas/schema_product.graphql
- graphql-cli/src/test/resources/graphqlServices/valid/service_11.bal
> Add subgraph tests and updates graphql timestamp version
> Link to the PR for changes to the training content in …
> Add SDL schema generation test for graphql subgraph

- gradle.properties
- graphql-cli/src/test/resources/graphqlServices/valid/service_11.bal
> $Subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Update graphql timestamp version

- gradle.properties
> Update lang version for 2201.8.0

- gradle.properties
> Update GraphQL Tool Version

- gradle.properties
> Update the Lang Version

- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
Fixes: [#234](https://github.com/ballerina-platform/graphql-tools/issues/234)
> [2201.3.x] Update Local Schema to Match with Remote Schema

- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
Fixes: [#234](https://github.com/ballerina-platform/graphql-tools/issues/234)
> [2201.4.x] Update the Schema to Match with Local Schema

- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/SpecReaderTest.java
- graphql-cli/src/test/resources/expectedGenCode/types.bal
- graphql-cli/src/test/resources/specs/schema.graphql
Fixes: [#234](https://github.com/ballerina-platform/graphql-tools/issues/234)
> [2201.5.x] Update the Local Schema to Match with Remote Schema

- gradle.properties
> Update the Lang Timestamp Version

- gradle.properties
Fixes: [#4942](https://github.com/ballerina-platform/ballerina-standard-library/issues/4942)
> Fix the Security Vulnerability Identified in 2201.6.x for json

- gradle.properties
Fixes:[#4942](https://github.com/ballerina-platform/ballerina-standard-library/issues/4942)
> Fix the Security Vulnerability Identified in 2201.7.x for json

- gradle.properties
Fixes: [#4942](https://github.com/ballerina-platform/ballerina-standard-library/issues/4942)
> Fix the Security Vulnerability Identified in 2201.8.2 for json

- build.gradle
Fixes: [#5794](https://github.com/ballerina-platform/ballerina-library/issues/5794)
> Remove unnecessary dependencies in gradle script

- build.gradle
> Update Gradle Script

- build.gradle
- gradle.properties
- graphql-cli/build.gradle
Fixes: [#5809](https://github.com/ballerina-platform/ballerina-library/issues/5809)
> Fix Security Vulnerability in GraphQL Tool

- gradle.properties
$title
fixes https://github.com/ballerina-platform/ballerina-release/issues/2599
> [2201.4.x] Fix dependency vulnerability

- gradle.properties
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_graphql_docs.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service_3.graphql
- graphql-cli/src/test/resources/expectedSchemas/schema_service_6.graphql
Fixes: [#5965](https://github.com/ballerina-platform/ballerina-library/issues/5965)
> Fix GraphQL Tool Test Failures

- gradle.properties
> Update the GraphQL Version

- gradle.properties
> Update the GraphQL Dependency Version

- gradle.properties
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesDocsWithInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceRecordsAllowed.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfacesImplementingInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithMultipleInterfacesDefault.bal
> Revert "Update Test Resource Files with Formatting Changes"

- gradle.properties
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesDocsWithInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceRecordsAllowed.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfacesImplementingInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithMultipleInterfacesDefault.bal
Fixes: [#6145](https://github.com/ballerina-platform/ballerina-library/issues/6145)
> Update Test Resource Files with Formatting Changes

- gradle.properties
> Bump the GraphQL version

- graphql-cli/build.gradle
- graphql-cli/src/main/java/module-info.java
> Add missing JAR dependencies

- build.gradle
- gradle.properties
> Migrate to new Runtime APIs

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Bump the Dependencies for Update 11 release

- gradle.properties
> Bump the version and GraphQL module version

- gradle.properties
> Bump the GraphQL library version

- graphql-tool/build.gradle
> Update Package User Details in Github Publish

- gradle.properties
- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-tool/Dependencies.toml
> Fix GraphQL-tool Test Failures

- .gitattributes
- .github/workflows/pull-request.yml
- gradle.properties
- graphql-cli/src/main/java/io/ballerina/graphql/cmd/GraphqlCmd.java
- graphql-cli/src/test/java/io/ballerina/graphql/cmd/GraphqlCmdTest.java
- graphql-tool/build.gradle
$Subject 
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8268
> Fix Graphql Tool Failure When No Argument is Passed
