- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/TypesGenerator.java
> Add support for alias
Resolves https://github.com/ballerina-platform/graphql-tools/issues/22
> Add support for alias
An example query which uses alias
```
query ExampleQuery2($code1: ID!, $code2: ID!, $code3: ID!) {
lk: country(code: $code1) {
code
name
}
au: country(code: $code2) {
code
native
}
continent(code: $code3) {
code
name
}
}
```
will generate the following record
```
type ExampleQuery2Response record {|
map<json?> __extensions?;
record {|
string code;
string name;
|}? lk;
record {|
string code;
string native;
|}? au;
record {|
string code;
string name;
|}? continent;
|};
```
> 
- If the alias is present, replace the record field name with this value
- Excape Ballerina keywords in alias
> Add support for alias
- Unit tests 
> None
> Done
- Followed secure …
> Add support for alias

- build.gradle
- graphql-cli/build.gradle
- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorUtils.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionSignatureGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/UtilsGenerator.java
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGeneratorTest.java
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/UtilsGeneratorTest.java
- graphql-cli/src/test/java/io/ballerina/graphql/generator/graphql/components/ExtendedOperationDefinitionTest.java
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/utils.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/utils.bal
- graphql-cli/src/test/resources/expectedGenCode/country_queries_client.bal
- graphql-cli/src/test/resources/specs/queries/country-queries.graphql
- graphql-cli/src/test/resources/testng.xml
> Add data binding logic
It was decided to remove the following response processing logic from the generic GraphQL client after the discussion with the Ballerina team, This PR provides all the necessary changes to move this logic to be handled in the generated client code.  
```
remote isolated function execute(typedesc<record {| json...; |}> returnType, string query, 
map<anydata>? variables = (), map<string|string[]>? headers = ()) 
returns record {| json...; |}|Error {
http:Request request = new;
json graphqlPayload = getGraphqlPayload(query, variables);
request.setPayload(graphqlPayload);
json|http:ClientError httpResponse = self.clientEp->post("", request, headers = headers);
do {
if httpResponse is http:ClientError {
if (httpResponse is http:ApplicationResponseError) {
anydata data …
```
> Add data binding logic

- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorConstants.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/CodeGeneratorUtils.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/ClientGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGenerator.java
- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/UtilsGenerator.java
- graphql-cli/src/main/resources/templates/utils.bal
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/FunctionBodyGeneratorTest.java
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/apiKeysConfig/utils.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/client/clientConfig/utils.bal
- graphql-cli/src/test/resources/expectedGenCode/country_queries_client.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignature.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignatureWithApiKeysAndClientConfig.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignatureWithApiKeysConfig.bal
- graphql-cli/src/test/resources/expectedGenCode/functionSignature/initFunctionSignatureWithClientConfig.bal
> 
Some modifications were done in the GraphQL generic client. We need to address those changes in the GraphQL client generation tool. This PR address those changes
Resolves https://github.com/ballerina-platform/graphql-tools/issues/32
> Address generic graphql client changes
> 
- Modify generic error `graphql:Error` as `graphql:ClientError` 
- Change the module org of the generic client from `ballerinax` to `ballerina`
- Modify function signature generator with changes to generic error
- Modify function body generator with changes to headers
- Modify utils generator to add the following imports and types
```
import ballerina/graphql;
type OperationResponse record {| anydata...; |}|record {| anydata...; |}[]|boolean|string|int|float|();
type DataResponse record {|
map<json?> …
```
> Address generic graphql client changes

- graphql-cli/src/main/java/io/ballerina/graphql/generator/ballerina/TypesGenerator.java
> 
Resolves https://github.com/ballerina-platform/graphql-tools/issues/34
> Add operation type name support
> 
- Handle operation type names for query and mutation in types generator
> Add operation type name support
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.0.1
Java SDK: 11
> Add operation type name support

- .github/workflows/build-timestamped-master.yml
- .github/workflows/publish-release.yaml
- .github/workflows/pull-request.yml
- .github/workflows/stale_check.yaml
- build.gradle
- config/checkstyle/build.gradle
- gradle.properties
- graphql-cli/build.gradle
- graphql-cli/src/main/java/io/ballerina/graphql/cmd/GraphqlCmd.java
- settings.gradle
> 
Resolves https://github.com/ballerina-platform/graphql-tools/issues/36
> Add support for GraphQL tool to pack with Ballerina distribution
> 
- Add necessary GitHub workflows
- Add release and GitHub package publish tasks to Gradle file
- Enable `commandUsageInfo`
- Bump tool version to `0.0.1-SNAPSHOT`
> Add support for GraphQL tool to pack with Ballerina distribution
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.0.1
Java SDK: 11
> Add support to pack the tool with Ballerina distribution

- gradle.properties
> Bump Ballerina version to 2201.0.2
Resolves https://github.com/ballerina-platform/graphql-tools/issues/52
> Bump Ballerina version to 2201.0.2
> Bump Ballerina version to 2201.0.2
> Bump Ballerina version to 2201.0.2
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.0.2
Java SDK: 11
> Bump Ballerina version to 2201.0.2

- gradle.properties
> Bump tool version to 0.0.3-SNAPSHOT
> 
Ballerina Version: 2201.0.2
Java SDK: 11
> Bump tool version to 0.0.3-SNAPSHOT

- gradle.properties
> Bump Ballerina version to 2201.0.3
Resolves https://github.com/ballerina-platform/graphql-tools/issues/55
> Bump Ballerina version to 2201.0.3
> Bump Ballerina version to 2201.0.3
> Bump Ballerina version to 2201.0.3
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.0.3
Java SDK: 11
> Bump ballerina version to 2201.0.3

- gradle.properties
> Bump tool version to 0.1.0-SNAPSHOT
> 
Ballerina Version: 2201.0.3
Java SDK: 11
> Bump tool version to 0.1.0-SNAPSHOT

- gradle.properties
> Bump Ballerina version to 2201.1.0-rc1.4
Resolves https://github.com/ballerina-platform/graphql-tools/issues/57
> Bump Ballerina version to 2201.1.0-rc1.4
> Bump Ballerina version to 2201.1.0-rc1.4
> Bump Ballerina version to 2201.1.0-rc1.4
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.1.0-rc1.4
Java SDK: 11
> Bump ballerina version to 2201.1.0-rc1.4

- gradle.properties
> Bump Ballerina version to 2201.1.0-rc1.7
Resolves https://github.com/ballerina-platform/graphql-tools/issues/60
> Bump Ballerina version to 2201.1.0-rc1.7
> Bump Ballerina version to 2201.1.0-rc1.7
> Bump Ballerina version to 2201.1.0-rc1.7
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.1.0-rc1.7
Java SDK: 11
> Bump ballerina version to 2201.1.0-rc1.7

- gradle.properties
> Bump Ballerina version to 2201.1.0-rc1.12
Resolves https://github.com/ballerina-platform/graphql-tools/issues/63
> Bump Ballerina version to 2201.1.0-rc1.12
> Bump Ballerina version to 2201.1.0-rc1.12
> Bump Ballerina version to 2201.1.0-rc1.12
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.1.0-rc1.12
Java SDK: 11
> Bump ballerina version to 2201.1.0-rc1.12

- gradle.properties
> Bump Ballerina version to 2201.1.0-rc1.13
Resolves https://github.com/ballerina-platform/graphql-tools/issues/65
> Bump Ballerina version to 2201.1.0-rc1.13
> Bump Ballerina version to 2201.1.0-rc1.13
> Bump Ballerina version to 2201.1.0-rc1.13
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.1.0-rc1.13
Java SDK: 11
> Bump ballerina version to 2201.1.0-rc1.13

- gradle.properties
> Bump tool version to 0.2.0-SNAPSHOT
> 
Ballerina Version: 2201.1.0
Java SDK: 11
> Bump tool version to 0.2.0-SNAPSHOT

- gradle.properties
> Bump Ballerina version to 2201.2.0-rc1.5
Resolves https://github.com/ballerina-platform/graphql-tools/issues/74
> Bump Ballerina version to 2201.2.0-rc1.5
> Bump Ballerina version to 2201.2.0-rc1.5
> Bump Ballerina version to 2201.2.0-rc1.5
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.2.0-rc1.5
Java SDK: 11
> Bump ballerina version to 2201.2.0-rc1.5

- gradle.properties
> Bump Ballerina version to 2201.2.0-rc2
Resolves https://github.com/ballerina-platform/graphql-tools/issues/78
> Bump Ballerina version to 2201.2.0-rc2
> Bump Ballerina version to 2201.2.0-rc2
> Bump Ballerina version to 2201.2.0-rc2
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.2.0-rc2
Java SDK: 11
> Bump ballerina version to 2201.2.0-rc2

- gradle.properties
> Bump Ballerina version to 2201.2.0-rc3
Resolves https://github.com/ballerina-platform/graphql-tools/issues/82
> Bump Ballerina version to 2201.2.0-rc3
> Bump Ballerina version to 2201.2.0-rc3
> Bump Ballerina version to 2201.2.0-rc3
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.2.0-rc3
Java SDK: 11
> Bump ballerina version to 2201.2.0-rc3

- graphql-cli/src/main/java/io/ballerina/graphql/cmd/GraphqlCmd.java
> Fix help flag (-h, --help) issue.
Resolves https://github.com/ballerina-platform/graphql-tools/issues/81
> Remove unexpected output in `bal graphql -h` command
> Use `exitError(this.exitWhenFinish);` instead of `return;`
> Remove unexpected output in `bal graphql -h` command
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.2.0-rc3
Java SDK: 11
> Fix help flag issue

- gradle.properties
> Bump Ballerina version to 2201.2.0-rc3.2
Resolves https://github.com/ballerina-platform/graphql-tools/issues/85
> Bump Ballerina version to 2201.2.0-rc3.2
> Bump Ballerina version to 2201.2.0-rc3.2
> Bump Ballerina version to 2201.2.0-rc3.2
- Unit tests 
> Done
> Done
> 
Ballerina Version: 2201.2.0-rc3.2
Java SDK: 11
> Bump ballerina version to 2201.2.0-rc3.2

- gradle.properties
> Bump tool version to 0.3.0-SNAPSHOT
> 
Ballerina Version: 2201.2.0
Java SDK: 11
> Bump tool version to 0.3.0-SNAPSHOT

- .github/workflows/pull-request.yml
- graphql-cli/build.gradle
- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-schema-file-generator/src/main/java/io/ballerina/graphql/schema/generator/SdlSchemaGenerator.java
1. Skip tests that are not compatible with the `windows` environment.
2. Skip schema generation for services with variable declaration when there is the `--service` is present in the CLI command. To generate the schema for these services, the command can be run without the `--service` flag. This is because of not having a way to filter the service declared as a variable by `service base path`.
> Skip Tests that not Compatible With Windows Environment

- graphql-cli/src/test/java/io/ballerina/graphql/cmd/SdlSchemaGenerationTest.java
- graphql-schema-file-generator/src/main/java/io/ballerina/graphql/schema/utils/NullLocation.java
>$subject 
Change the location value return for the errors that do not have a proper location. The location `ERROR [:(1:1,1:1)]` is changed as `ERROR [:(-1:-1,-1:-1)]`.
> Update the Location Returns for Errors

- graphql-cli/src/test/java/io/ballerina/graphql/cmd/GraphqlCmdTest.java
- graphql-cli/src/test/resources/specs/graphql-schema-with-subscription.yaml
- graphql-cli/src/test/resources/specs/graphql-schema-with-unsupported-operations.yaml
- graphql-cli/src/test/resources/specs/queries/scalar-queries.graphql
- graphql-cli/src/test/resources/specs/queries/subscription-queries.graphql
- graphql-cli/src/test/resources/specs/schema-with-scalar.graphql
- graphql-cli/src/test/resources/specs/schema-with-subscription.graphql
- graphql-code-generator/src/main/java/io/ballerina/graphql/generator/client/generator/ClientCodeGenerator.java
Fixes: [#229](https://github.com/ballerina-platform/graphql-tools/issues/229)
```shell
ERROR [(root:):(1:1,1:1)] Ballerina code generation related error occurred. The provided schema includes operations that are not supported by the client generation.
Please check project : root
```
> Return a Proper Error Message for Unsupported Operations

- README.md
Fixes: [#6042](https://github.com/ballerina-platform/ballerina-library/issues/6042)
> Mark GraphQL Client Generation Feature as Experimental

- gradle.properties
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesDocsWithInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfaceRecordsAllowed.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithInterfacesImplementingInterfacesDefault.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithMultipleInterfacesDefault.bal
Fixes: [#6145](https://github.com/ballerina-platform/ballerina-library/issues/6145)
> Update Test Resource Files with Formatting Changes

- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/ServiceGeneratorTest.java
- graphql-cli/src/test/java/io/ballerina/graphql/generator/ballerina/ServiceTypesGeneratorTest.java
- graphql-cli/src/test/resources/serviceGen/expectedServices/serviceForSchemaWithIDTypeApi.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithIDTypeRecordsAllowed.bal
- graphql-cli/src/test/resources/serviceGen/expectedServices/typesWithMutationDefault.bal
- graphql-cli/src/test/resources/serviceGen/graphqlSchemas/valid/SchemaWithIDTypeApi.graphql
- graphql-code-generator/src/main/java/io/ballerina/graphql/generator/service/generator/ServiceTypesGenerator.java
Fixes: [#6381](https://github.com/ballerina-platform/ballerina-library/issues/6381)
> Link(s) to product documentation that …
> Annotate GraphQL ID Types with `@graphql:ID` Annotation in Service Generation
